apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: app2-tls
  labels:
    f5cr: "true"
spec:
  tls:
    termination: edge
    clientSSL: /Common/clientssl
#    serverSSL: /Common/serverssl
    reference: bigip             # --> reference profiles created in BIG-IP by User
  hosts:
  - app2.f5demo.cloud