apiVersion: v1
kind: Service
metadata:
  name: app-svc-1
  labels:
    app: app-svc-1
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: app-1

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-2
  labels:
    app: app-svc-2
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: app-2

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-3
  labels:
    app: app-svc-3
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: app-3

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-4
  labels:
    app: app-svc-4
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: app-4

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc-5
  labels:
    app: app-svc-5
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: app-5
