---
- hosts: master
  gather_facts: no
  tasks:    
  - name: Download Git Repository
    git:
      repo: https://github.com/skenderidis/f5-cis-lab
      dest: /home/{{ansible_user}}/f5-cis-lab

  - name: Move kubernetes to different directory
    command: mv /home/{{ansible_user}}/f5-cis-lab/kubernetes /home/{{ansible_user}}/kubernetes

  - name: Remove Git
    file: path=/home/{{ansible_user}}/f5-cis-lab state=absent

  - name: Deploy Apps and Services
    command: kubectl apply -f kubernetes/1-apps

  - name: Deploy Nginx RBAC
    command: kubectl apply -f kubernetes/2-Nginx-RBAC

  - name: Deploy NGINX Resources
    command: kubectl apply -f kubernetes/3-Nginx-Resources

  - name: Deploy NGINX CRDs
    command: kubectl apply -f kubernetes/4-Nginx-CRDs

  - name: Deploy NGINX Controller
    command: kubectl apply -f kubernetes/5-Nginx-Deployments

#  - name: Deploy CIS Resources (CRD mode)
#    command: kubectl apply -f kubernetes/6-cis
